databases:
  - name: gymapp-db
    databaseName: gymapp
    user: gymapp

services:
  - type: web
    name: gymapp
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn gainz.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: DATABASE_URL
        fromDatabase:
          name: gymapp-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false