# Generated by Django 5.1.7 on 2025-04-20 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='category',
        ),
        migrations.AddField(
            model_name='exercise',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='exercises', to='exercises.exercisecategory'),
        ),
    ]
