# Generated by Django 3.2.25 on 2025-08-19 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_exercise_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseAlternativeName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_primary', models.BooleanField(default=False, help_text='If True, this is the main alternative name')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternative_names', to='exercises.exercise')),
            ],
            options={
                'verbose_name_plural': 'Exercise Alternative Names',
                'unique_together': {('exercise', 'name')},
            },
        ),
    ]
