# Generated by Django 3.2.25 on 2025-09-09 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_exercisealternativename'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='primary_bodypart',
            field=models.CharField(blank=True, choices=[('chest', 'Chest'), ('back', 'Back'), ('shoulders', 'Shoulders'), ('arms', 'Arms'), ('legs', 'Legs'), ('glutes', 'Glutes'), ('core', 'Core'), ('cardio', 'Cardio'), ('full_body', 'Full Body')], help_text='Primary muscle group targeted by this exercise', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='secondary_bodypart',
            field=models.CharField(blank=True, choices=[('chest', 'Chest'), ('back', 'Back'), ('shoulders', 'Shoulders'), ('arms', 'Arms'), ('legs', 'Legs'), ('glutes', 'Glutes'), ('core', 'Core'), ('cardio', 'Cardio'), ('full_body', 'Full Body')], help_text='Secondary muscle group targeted by this exercise', max_length=20, null=True),
        ),
    ]
