# Generated by Django 5.1.7 on 2025-05-20 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_workoutexercise_performance_feedback_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routine',
            name='program',
        ),
        migrations.RemoveField(
            model_name='routineexercise',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='routineexercise',
            name='progression_strategy_notes',
        ),
    ]
