# Generated by Django 5.1.7 on 2025-05-23 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_remove_routine_program_remove_routineexercise_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routineexercise',
            name='target_reps',
        ),
        migrations.RemoveField(
            model_name='routineexercise',
            name='target_rest_seconds',
        ),
        migrations.RemoveField(
            model_name='routineexercise',
            name='target_sets',
        ),
        migrations.AddField(
            model_name='routineexercise',
            name='routine_specific_exercise_type',
            field=models.CharField(blank=True, choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('accessory', 'Accessory')], help_text='Override the default exercise type for this routine.', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='RoutineExerciseSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.PositiveIntegerField()),
                ('target_reps', models.CharField(blank=True, help_text='e.g., "8-12", "AMRAP", "5"', max_length=50)),
                ('target_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('target_rpe', models.DecimalField(blank=True, decimal_places=1, help_text='Rate of Perceived Exertion (e.g., 7.5)', max_digits=3, null=True)),
                ('rest_time_seconds', models.PositiveIntegerField(blank=True, help_text='Rest time in seconds after this set', null=True)),
                ('notes', models.TextField(blank=True)),
                ('routine_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_sets', to='workouts.routineexercise')),
            ],
            options={
                'ordering': ['set_number'],
                'unique_together': {('routine_exercise', 'set_number')},
            },
        ),
    ]
