# Generated by Django 5.1.7 on 2025-05-27 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_remove_routineexercise_target_reps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='day_of_week',
            field=models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of the week this routine is typically performed.', null=True),
        ),
        migrations.AddField(
            model_name='routine',
            name='sequence_order',
            field=models.PositiveIntegerField(blank=True, help_text='Order in a sequence (e.g., 1 for A, 2 for B in an A/B split).', null=True),
        ),
    ]
