# Generated by Django 5.1.7 on 2025-05-27 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_routine_day_of_week_routine_sequence_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routine',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='sequence_order',
        ),
        migrations.AddField(
            model_name='program',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ProgramRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='Order of the routine within the program (e.g., 1, 2, 3). Used if not assigning by day.')),
                ('assigned_day', models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Specific day of the week this routine is scheduled for in this program.', null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_routines', to='workouts.program')),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_associations', to='workouts.routine')),
            ],
            options={
                'ordering': ['program', 'order', 'assigned_day'],
                'unique_together': {('program', 'routine')},
            },
        ),
    ]
