# Generated by Django 3.2.25 on 2025-07-15 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_remove_routine_day_of_week_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='scheduling_type',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('sequential', 'Sequential')], default='weekly', max_length=10),
        ),
    ]
