# Generated by Django 3.2.25 on 2025-07-15 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0007_program_scheduling_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='programroutine',
            unique_together=set(),
        ),
    ]
