# Generated by Django 3.2.25 on 2025-09-09 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_exercisealternativename'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workouts', '0008_alter_programroutine_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTimerPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_timer_seconds', models.PositiveIntegerField(default=180, help_text='Default rest timer for primary exercises in seconds')),
                ('secondary_timer_seconds', models.PositiveIntegerField(default=120, help_text='Default rest timer for secondary exercises in seconds')),
                ('accessory_timer_seconds', models.PositiveIntegerField(default=90, help_text='Default rest timer for accessory exercises in seconds')),
                ('auto_start_timer', models.BooleanField(default=False, help_text='Automatically start timer after logging a set')),
                ('timer_sound_enabled', models.BooleanField(default=True, help_text='Play sound when timer completes')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timer_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Timer Preference',
                'verbose_name_plural': 'User Timer Preferences',
            },
        ),
        migrations.CreateModel(
            name='ExerciseTimerOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timer_seconds', models.PositiveIntegerField(help_text='Custom rest timer for this exercise in seconds')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_timer_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exercise Timer Override',
                'verbose_name_plural': 'Exercise Timer Overrides',
                'unique_together': {('user', 'exercise')},
            },
        ),
    ]
