# Generated by Django 3.2.25 on 2025-09-09 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0009_add_timer_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertimerpreference',
            name='preferred_weight_unit',
            field=models.CharField(choices=[('kg', 'Kilograms'), ('lbs', 'Pounds')], default='kg', help_text='Preferred unit for displaying and entering weights', max_length=3),
        ),
    ]