# Generated by Django 3.2.25 on 2025-09-09 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0010_add_preferred_weight_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertimerpreference',
            name='auto_progression_enabled',
            field=models.BooleanField(default=False, help_text='Automatically adjust weights/reps based on performance feedback'),
        ),
        migrations.AddField(
            model_name='usertimerpreference',
            name='default_rep_increment',
            field=models.PositiveIntegerField(default=1, help_text="Default rep increment for auto-progression when weight can't be increased"),
        ),
        migrations.AddField(
            model_name='usertimerpreference',
            name='default_weight_increment',
            field=models.DecimalField(decimal_places=2, default=2.5, help_text='Default weight increment for auto-progression (e.g., 2.5 kg/lbs)', max_digits=6),
        ),
    ]
