# Generated by Django 3.2.25 on 2025-09-09 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_auto_20250909_2346'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workouts', '0011_auto_20250909_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('1rm', '1 Rep Max'), ('volume', 'Volume Record'), ('endurance', 'Endurance Record')], default='1rm', max_length=20)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight used for the record', max_digits=6)),
                ('reps', models.PositiveIntegerField(help_text='Reps achieved for the record')),
                ('date_achieved', models.DateTimeField(auto_now_add=True)),
                ('video', models.FileField(blank=True, help_text='Optional video proof of the personal record', null=True, upload_to='personal_records/videos/%Y/%m/')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this record')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='exercises.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_records', to=settings.AUTH_USER_MODEL)),
                ('workout_exercise_source', models.ForeignKey(blank=True, help_text='The workout exercise that achieved this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_records_achieved', to='workouts.workoutexercise')),
            ],
            options={
                'verbose_name': 'Personal Record',
                'verbose_name_plural': 'Personal Records',
                'ordering': ['-date_achieved'],
                'unique_together': {('user', 'exercise', 'record_type')},
            },
        ),
    ]
