# Generated by Django 3.2.25 on 2025-09-09 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0012_personalrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutineTimerPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_timer_seconds', models.PositiveIntegerField(blank=True, help_text='Routine-specific timer for primary exercises in seconds', null=True)),
                ('secondary_timer_seconds', models.PositiveIntegerField(blank=True, help_text='Routine-specific timer for secondary exercises in seconds', null=True)),
                ('accessory_timer_seconds', models.PositiveIntegerField(blank=True, help_text='Routine-specific timer for accessory exercises in seconds', null=True)),
                ('auto_start_timer', models.BooleanField(blank=True, help_text='Routine-specific auto-start timer preference', null=True)),
                ('routine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timer_preferences', to='workouts.routine')),
            ],
            options={
                'verbose_name': 'Routine Timer Preference',
                'verbose_name_plural': 'Routine Timer Preferences',
            },
        ),
        migrations.CreateModel(
            name='ProgramTimerPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_timer_seconds', models.PositiveIntegerField(blank=True, help_text='Program-specific timer for primary exercises in seconds', null=True)),
                ('secondary_timer_seconds', models.PositiveIntegerField(blank=True, help_text='Program-specific timer for secondary exercises in seconds', null=True)),
                ('accessory_timer_seconds', models.PositiveIntegerField(blank=True, help_text='Program-specific timer for accessory exercises in seconds', null=True)),
                ('auto_start_timer', models.BooleanField(blank=True, help_text='Program-specific auto-start timer preference', null=True)),
                ('program', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timer_preferences', to='workouts.program')),
            ],
            options={
                'verbose_name': 'Program Timer Preference',
                'verbose_name_plural': 'Program Timer Preferences',
            },
        ),
    ]
