# Generated by Django 3.2.25 on 2025-09-09 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0013_add_program_routine_timer_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', help_text='Who can see this workout', max_length=10),
        ),
    ]
